<link rel="stylesheet" href="https://devcloud.productimize.com/productimizedemo/productimize/PZStyle.css" />
<?php
$productId = (int) $this->getRequest()->getParam('product');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$siteUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$siteUrl = preg_replace('#^https?://#', '', $siteUrl);
$siteUrl = preg_replace('/^www\./', '', $siteUrl);
$siteUrl = rtrim($siteUrl, '/');

$domainName = $siteUrl;
?>

<input type="hidden" name="web_product_id" id="web_product_id" value="<?php echo $productId; ?>" />
<script> 
    window.shop_name = "<?php echo $domainName;?>";
</script>


<div id="root">
</div>

    <script>

    require(['jquery', 'jquery/ui', 'react', 'reactdom', 'babel', 'fabric'],
        function ($, jqyeryui,React, ReactDOM, babel, fabric) {
            console.log("coming inside script")
            window.React = React;
            window.ReactDOM = ReactDOM;
            $.getScript("https://devcloud.productimize.com/identiphoto/identiphoto/Promize-Template1/libraries/customiseControls.min.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PromizeCloud.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PZOption.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PZText.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PZUploadImage.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PZClipart.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PZCart.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PZSubTab.js", function () {});

            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PZTab.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PZViews.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PZSection.js", function () {});

            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PZMailShare.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PZHome.js", function () {})

            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PromizeOption.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PromizeJsColor.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PromizeText.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PromizeUploadImage.js", function () {});

            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PromizeClipart.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PromizeAttribute.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PromizeCart.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PromizeSubTab.js", function () {});


            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PromizeTab.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PromizeSection.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PromizeViews.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PromizeMailShare.js", function () {});

            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PromizeHome.js", function () {});
            $.getScript("https://devcloud.productimize.com/productimizedemo/productimize/PromizeCanvas.js", function () {});
            //jQuery('body').trigger('processStop');
            $(document).ready(function(){
                $('body').on('click', '.add-item-cart', function (){
                    if(!$(this).hasClass('add-item-cart-disabled disabled') && $('.add-item-cart').length > 0){


                        var productimize_response = window.PZaddToCartDetails();
                        // console.log(productimize_response)
                        let jsonResponse = JSON.parse(productimize_response);
                        // console.log(jsonResponse.orderObject);
                       // return false;
                        $("#productimize_response").val(jsonResponse.orderObject);
                        $("#domain_id").val(jsonResponse.domain_id);
                        $("#customizer_id").val(jsonResponse.customizer_id);
                        // var productimize_response = window.PZaddToCartDetails();
                        // $("#productimize_response").val(productimize_response);
                        $('.box-tocart').css('display', 'block');
                        $('#productimize_container').html("");    
                        $('#productimize_customize_button').css('display', 'block');
                        $('.media').css('display', 'block');
                        $('.productimize_container').next().css('display', 'block');
                        $('.description').css('display', 'block');
                        $('.overview').css('display', 'block');
                        $('#sample_images_custom_product').css('display', 'block');
                        $(".product-detail-section").removeClass("product-detail-customize-section");
                        $("#product_addtocart_form").submit();
                        $("#productimize_response").val("");
                    }
                });
                $('body').on('click', '#goback', function (){
                    if($('#goback').length > 0){
                        $('.box-tocart').css('display', 'block')
                        $('#productimize_container').html("");    
                        $('#productimize_customize_button').css('display', 'block');
                        $('.media').css('display', 'block');
                        $('.productimize_container').next().css('display', 'block');
                        $('.description').css('display', 'block');
                        $('.overview').css('display', 'block');
                        $('#sample_images_custom_product').css('display', 'block');
                        $(".product-detail-section").removeClass("product-detail-customize-section");
                    }
                });
            });
        });

</script>



