<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<?php $defaultConf = $block->getProduct()->getData('default_configurations');?>
<div class="pz-product-container" id="pz-product-container">
    <!--<div class="pz-display-price" id="pz-display-price" >$ <?php /*echo number_format($block->getProduct()->getPrice(), 2, '.', ''); */?></div>-->
    <div class="pz-display-button-grp">
        <button type="button" class="pz-room active" id="magento_customize_button">
            <i class="fa fa-eye" aria-hidden="true"></i>
        <?php echo $block->escapeHtml(__('View in Room'));
        ?>
        </button>
        <button type="button" class="pz-customize" id="productimize_customize_button">
            <i class="fa fa-paint-brush" aria-hidden="true"></i>
        <?php echo $block->escapeHtml(__('Customize'));
        ?>
        </button>
        <button type="button" class="pz-cancel" id="productimize_customize_cancel_button" style="display:none">
            <i class="fa fa-paint-brush" aria-hidden="true"></i>
            <?php echo $block->escapeHtml(__('Cancel'));
            ?>
        </button>
    </div>
</div>
<input type="hidden" value='<?php echo $defaultConf;?>' id="pz_magento_default_options" />
<input type="hidden" value='<?php echo $block->getProduct()->getData('product_level');?>' id="pz_platform_product_level" />
<div class="pz_data" id="pz_data">


<?php

$parsedDefCon = json_decode($defaultConf, 1);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productFactory = $objectManager->create('Magento\Catalog\Model\ProductFactory');
$_imageHelper = $objectManager->get('Magento\Catalog\Helper\Image');
foreach ($parsedDefCon as $key => $value) {

    $keyRemoved = trim(str_replace("default_sku", "", $key));

    $currProduct = $productFactory->create()->loadByAttribute('sku', $value);
    if (isset($currProduct) && !empty($currProduct) && $currProduct->getId()) {

       $imageUrl = $_imageHelper->init($currProduct, 'small_image', ['type'=>'small_image'])->keepAspectRatio(true)->resize('50','50')->getUrl();

        echo "<div class='pz-default'>";
        echo "<div class='pz-default-head'>";
        echo ucfirst(str_replace("_", " ", $keyRemoved));
        echo "</div>";
        echo "<div><img width='50' height='50' src='".$imageUrl."'/></div>";
        echo "<div class='pz-default-val'>" . $value .'</div></div>';

    }


}

?>
<br/>
</div>
<?php $magentoProductId = $block->getProduct()->getId();//17 ?>
<input type="hidden" name="pz_objects" id="pz_objects" value="" />
<input type="hidden" name="pz_cart_properties" id="pz_cart_properties" value="" />
<div id="productimize_container"></div>

<style>

    #block-upsell-heading {
        display:none;
    }
    .pz-product-container {
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin-bottom: 1.5rem;
    }

    .pz_product_info_main button {
        text-transform: uppercase;
        padding: 1.5rem 2.5rem;
        box-shadow: none !important;
        margin-left: 1rem;
    }

    .pz-display-price {
        color: #b71804;
        font-weight: 600;
        font-size: 25px;
    }

    .pz-customize {
        background: #757063;
        color: white;
        border-color: #757063;
    }

    .pz-room {
        background: white;
        border-color: #d8d9d7;
        color: #757063;
    }

    .pz-cancel {
        background: #d8d9d7;
        color: #4c4d4f;
        border-color: #d8d9d7;
    }

    #product-price-1 .price,
    span.price-container.price-final_price.tax.weee,
    .product-info-stock-sku .stock.available {
        display: none;
    }

    .box-tocart {
        margin: 1rem 0;
    }

    .box-tocart .fieldset {
        display: flex;
        align-items: center;
        border-top: 1px solid #c9c9c9;
        border-bottom: 1px solid #c9c9c9;
        padding: 1rem 0;
    }


    .field.qty {
        display: flex !important;
        align-items: center !important;
        margin: 0 !important;
        margin-right: 3rem !important;
    }

    .field.qty .label {
        margin-right: 1rem !important;
    }

    .field.qty .control input {
        height: 53px;
        border-radius: 5px;
    }

    .box-tocart .actions {
        width: 100%
    }

    #product-addtocart-button {
        background: #b71804;
        text-transform: uppercase;
        border-color: #b71804;
        margin: 0;
    }

    .product-info-main .product-info-price {
        border-bottom: 1px solid #c9c9c9 !important;
    }

    .product.attribute.sku {
        color: #919191;
    }

    .page-title-wrapper.product .page-title {
        color: #010101;
    }

    .product-add-form {
        padding: 0 !important;
    }

    .pz_data p{
        color: #4e4f51;
        margin-bottom: 2rem;
    }

    .pz-default {
        display: flex;
        margin: 1rem 0;
    }

    .pz-default-head {
        color: #4c4d4f;
        margin-right: 1rem;
    }

    .pz-default-val{
        margin-left: 0.3rem;
    }
    .pz-display-button-grp.pz_product_info_main {
        display: flex;
    }


    .pz-hover > div {
        position: relative;
    }
    .pz-hover > div:before {
        position: absolute;
        content: "";
        top: -7px;
        left: 2px;
        border: 7px solid transparent;
        border-top: 0;
        border-bottom-color: #333333;
    }
    .pz-hover {
        position: fixed;
        display: none;
        border: 0;
        z-index: 10;
        color: #fff;
        word-break: break-word;
        font-size: 11px;
        font-weight: bold;
        background-color: #333333;
        align-items: center;
        justify-content: center;
        text-align: center;
        line-height: 16px;
        -webkit-box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.28);
        -moz-box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.28);
        -ms-box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.28);
        -o-box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.28);
        padding: 4px 5px;
        border-radius: 4px;
        max-width: 300px;
        width: auto;
    }


    @media screen and (max-width: 768px) {
    .customize-button {  
        width: 100%;
    }



}
</style>
<script type="text/javascript">

    require(
        [
            'jquery',
            'mage/validation'
        ],
        function ($,
                  validation) {

            'use strict';



            // for styles
            var info_main = $('#productimize_customize_button').parent();
            info_main.addClass('pz_product_info_main');

            // Click of add customization button

            $("#productimize_customize_button").on('click', function () {
                    jQuery('body').trigger('processStart');

                $('#magento_customize_button').removeClass('active');


                if ($('#product_addtocart_form').find('#pz_objects').length === 0) {
                    $('#product_addtocart_form').append($('#pz_objects'));
                }
                if ($('#product_addtocart_form').find('#pz_cart_properties').length === 0) {
                    $('#product_addtocart_form').append($('#pz_cart_properties'));
                }




                var productimizeCustomizationUrl = 'productimize/index/index';

                    $.ajax({
                        showLoader: false,
                        url: productimizeCustomizationUrl,
                        data: {
                            product: "<?php echo $magentoProductId;?>",
                            //product: $('.price-box').attr('data-product-id'),
                           // optAttributes: attributes,
                            //selectedAttributes: selectedOptAttr,
                            isAjax: 1
                        },
                        type: "POST",
                        //dataType: 'json',
                        success: function (data) {
                            jQuery('body').trigger('processStop');



                            //$("#productimize_response").val("");
                            //$('.pz_product_info_main').css('width', '100%');
                            //$(".page-title-wrapper.product").css('float', 'right');
                           // $(".reviews-actions").css('display', 'none');
                            //$(".product-social-links").css('display', 'none');


                            //


                            //$('.pz-custom-content-wrapper').append('<div class="magento-heading"><h1></h1> <p></p></div>')


                            $('.box-tocart').css('display', 'none')
                            $('#productimize_container').html(data.content);
                            $('#productimize_customize_button').css('display', 'none');
                            $('.media').css('display', 'none');
                            //$('.productimize_container').html(data.content);
                            $('.productimize_container').next().css('display', 'none');
                            $('.description').css('display', 'none');
                            $('.overview').css('display', 'none');
                            $(".product-detail-section").addClass("product-detail-customize-section");
                            $('#sample_images_custom_product').css('display', 'none');

                            $('#productimize_customize_cancel_button').css("display", "block")
                            $('#pz_data').css("display", "none");

                            $('#pz-display-price').css("visibility", "hidden");


                            //$('#pz-product-container').prependTo('.pz-custom-content-wrapper')
                            //  $('<div class="magento-heading"><h1>heading</h1> <p>sku</p></div>').prependTo('.pz-custom-content-wrapper')




                        },
                        error: function () {
                            jQuery('body').trigger('processStop');
                            alert('Error occurred');
                        }
                    });

            });


            $("#productimize_customize_cancel_button").on('click', function () {

                $('#magento_customize_button').addClass('active');


                $('.box-tocart').css('display', 'block')
                $('#productimize_container').html("");
                $('#productimize_customize_button').css('display', 'block');
                $('.media').css('display', 'block');
                //$('.productimize_container').html(data.content);
                $('.productimize_container').next().css('display', 'block');
                $('.description').css('display', 'block');
                $('.overview').css('display', 'block');
                //$(".product-detail-section").addClass("product-detail-customize-section");
                $('#sample_images_custom_product').css('display', 'block');

                $('#productimize_customize_cancel_button').css("display", "none")
                $('#pz_data').css("display", "block")
                $('#pz-display-price').css("visibility", "visible");

            });

            $("#magento_customize_button").on('click', function () {

                $('#magento_customize_button').addClass('active');


                $('.box-tocart').css('display', 'block')
                $('#productimize_container').html("");
                $('#productimize_customize_button').css('display', 'block');
                $('.media').css('display', 'block');
                //$('.productimize_container').html(data.content);
                $('.productimize_container').next().css('display', 'block');
                $('.description').css('display', 'block');
                $('.overview').css('display', 'block');
                //$(".product-detail-section").addClass("product-detail-customize-section");
                $('#sample_images_custom_product').css('display', 'block');

                $('#productimize_customize_cancel_button').css("display", "none");
                $('#pz_data').css("display", "block")
                $('#pz-display-price').css("visibility", "visible");

            });


        });


</script>